// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/eventsourcing/commandhandler_service.proto

package eventsourcing

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CommandReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CommandReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CommandReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CommandReplyMultiError, or
// nil if none found.
func (m *CommandReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CommandReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AggregateId

	// no validation rules for Version

	if len(errors) > 0 {
		return CommandReplyMultiError(errors)
	}
	return nil
}

// CommandReplyMultiError is an error wrapping multiple validation errors
// returned by CommandReply.ValidateAll() if the designated constraints aren't met.
type CommandReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CommandReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CommandReplyMultiError) AllErrors() []error { return m }

// CommandReplyValidationError is the validation error returned by
// CommandReply.Validate if the designated constraints aren't met.
type CommandReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CommandReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CommandReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CommandReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CommandReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CommandReplyValidationError) ErrorName() string { return "CommandReplyValidationError" }

// Error satisfies the builtin error interface
func (e CommandReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCommandReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CommandReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CommandReplyValidationError{}
